-- View: foncier.mv_ep_geo2af_grid2d

DROP MATERIALIZED VIEW foncier.mv_ep_geo2af_grid2d;
CREATE MATERIALIZED VIEW foncier.mv_ep_geo2af_grid2d
AS
 SELECT foo3.ogc_fid,
    foo3.ep_id,
	COUNT(*) OVER(PARTITION BY foo3.id_af) AS nb_cartes,
    foo3.ep_nom,
    foo3.nb_parcelles_signees,
    foo3.list_parcelles_signees,
    foo3.projet_id,
    foo3.projet_nom,
    foo3.projet_statut,
    foo3.id_af,
    foo3.nom_fichier,
    foo3.bail_de_fermage,
    foo3.type_accord,
    foo3.type_redevance,
    foo3.conditions_particulieres,
    foo3.date_effet,
    foo3.date_enregistrement,
    foo3.redevance,
    foo3.jours_restants_avant_prorog,
    foo3.statut_action,
    foo3.af_date_validite,
    foo3.nombre_avenant,
    foo3.date_validite,
    foo3.date_limite_envoi_prorog,
    foo3.prorogation,
    foo3.prorog_date_fin,
    foo3.prorog_nom_fichier,
    foo3.jours_restants,
    foo3.lib_action,
    foo3.wkb_geometry,
    foo3.sub_num_id_af,
        CASE
            WHEN foo3.sub_num_id_af = 1 THEN false
            ELSE true
        END AS page_exclude
   FROM ( SELECT foo2.ogc_fid,
            foo2.ep_id,
            foo2.ep_nom,
            foo2.nb_parcelles_signees,
            foo2.list_parcelles_signees,
            foo2.projet_id,
            foo2.projet_nom,
            foo2.projet_statut,
            foo2.id_af,
            foo2.nom_fichier,
            foo2.bail_de_fermage,
            foo2.type_accord,
            foo2.type_redevance,
            foo2.conditions_particulieres,
            foo2.date_effet,
            foo2.date_enregistrement,
            foo2.redevance,
            foo2.jours_restants_avant_prorog,
            foo2.statut_action,
            foo2.af_date_validite,
            foo2.nombre_avenant,
            foo2.date_validite,
            foo2.date_limite_envoi_prorog,
            foo2.prorogation,
            foo2.prorog_date_fin,
            foo2.prorog_nom_fichier,
            foo2.jours_restants,
            foo2.lib_action,
            foo2.wkb_geometry,
            row_number() OVER (PARTITION BY foo2.id_af) AS sub_num_id_af
           FROM ( SELECT row_number() OVER () AS ogc_fid,
                    foo.ep_id,
                    foo.ep_nom,
                    foo.nb_parcelles_signees,
                    foo.list_parcelles_signees,
                    foo.projet_id,
                    foo.projet_nom,
                    foo.projet_statut,
                    foo.id_af,
                    foo.nom_fichier,
                    foo.bail_de_fermage,
                    foo.type_accord,
                    foo.type_redevance,
                    foo.conditions_particulieres,
                    foo.date_effet,
                    foo.date_enregistrement,
                    foo.redevance,
                    foo.jours_restants_avant_prorog,
                    foo.statut_action,
                    foo.af_date_validite,
                    foo.nombre_avenant,
                    foo.date_validite,
                    foo.date_limite_envoi_prorog,
                    foo.prorogation,
                    foo.prorog_date_fin,
                    foo.prorog_nom_fichier,
                    foo.jours_restants,
                    foo.lib_action,
                    foo.grid_geom AS wkb_geometry
                   FROM ( SELECT a.ep_id,
                            a.ep_nom,
                            a.nb_parcelles_signees,
                            a.list_parcelles_signees,
                            a.projet_id,
                            a.projet_nom,
                            a.projet_statut,
                            a.id_af,
                            a.nom_fichier,
                            a.bail_de_fermage,
                            a.type_accord,
                            a.type_redevance,
                            a.conditions_particulieres,
                            a.date_effet,
                            a.date_enregistrement,
                            a.redevance,
                            a.jours_restants_avant_prorog,
                            a.statut_action,
                            a.af_date_validite,
                            a.nombre_avenant,
                            a.date_validite,
                            a.date_limite_envoi_prorog,
                            a.prorogation,
                            a.prorog_date_fin,
                            a.prorog_nom_fichier,
                            a.jours_restants,
                            a.lib_action,
                            a.ep_geom,
                            st_transform((a.grid_geom_wgs84).geom, 2154)::geometry(Polygon,2154) AS grid_geom
                           FROM ( SELECT v_ep_geo2af.ep_id,
                                    v_ep_geo2af.ep_nom,
                                    v_ep_geo2af.nb_parcelles_signees,
                                    v_ep_geo2af.list_parcelles_signees,
                                    v_ep_geo2af.projet_id,
                                    v_ep_geo2af.projet_nom,
                                    v_ep_geo2af.projet_statut,
                                    v_ep_geo2af.id_af,
                                    v_ep_geo2af.nom_fichier,
                                    v_ep_geo2af.bail_de_fermage,
                                    v_ep_geo2af.type_accord,
                                    v_ep_geo2af.type_redevance,
                                    v_ep_geo2af.conditions_particulieres,
                                    v_ep_geo2af.date_effet,
                                    v_ep_geo2af.date_enregistrement,
                                    v_ep_geo2af.redevance,
                                    v_ep_geo2af.jours_restants_avant_prorog,
                                    v_ep_geo2af.statut_action,
                                    v_ep_geo2af.af_date_validite,
                                    v_ep_geo2af.nombre_avenant,
                                    v_ep_geo2af.date_validite,
                                    v_ep_geo2af.date_limite_envoi_prorog,
                                    v_ep_geo2af.prorogation,
                                    v_ep_geo2af.prorog_date_fin,
                                    v_ep_geo2af.prorog_nom_fichier,
                                    v_ep_geo2af.jours_restants,
                                    v_ep_geo2af.lib_action,
                                    v_ep_geo2af.wkb_geometry AS ep_geom,
                                    st_dump(makegrid_2d(st_transform(st_buffer(v_ep_geo2af.wkb_geometry, 1500::double precision), 4326), 4275, 4275)) AS grid_geom_wgs84
                                   FROM foncier.v_ep_geo2af) a) foo
                  WHERE st_intersects(st_buffer(foo.ep_geom, 1::double precision), foo.grid_geom)) foo2) foo3
  ORDER BY foo3.projet_id, foo3.id_af, foo3.ogc_fid	
WITH DATA;

ALTER TABLE foncier.mv_ep_geo2af_grid2d
    OWNER TO sdi_user2;

GRANT SELECT ON TABLE foncier.mv_ep_geo2af_grid2d TO PUBLIC;
GRANT ALL ON TABLE foncier.mv_ep_geo2af_grid2d TO sdi_user2;

CREATE INDEX sidx_mv_ep_geo2af_grid2d
    ON foncier.mv_ep_geo2af_grid2d USING gist
    (wkb_geometry)
    TABLESPACE pg_default;
CREATE UNIQUE INDEX uidx_mv_ep_geo2af_grid2d
    ON foncier.mv_ep_geo2af_grid2d USING btree
    (ogc_fid)
    TABLESPACE pg_default;