CREATE OR REPLACE VIEW wind_measurement.v_met_mast_axes_complete AS
SELECT
ogc_fid,
nom,
description,
id_projet,
ST_Buffer(ST_Union(ARRAY[geom_buffer_axe1,geom_buffer_axe2,geom_buffer_axe3,geom_buffer_axe4,geom_buffer_pied_mat]),0)::geometry(Polygon,2154) as wkb_geometry
FROM(SELECT v_buffer.ogc_fid,
v_buffer.nom,
v_buffer.description,
v_buffer.id_projet,
ST_Buffer(axe1_rotated_geometry,(v_buffer.largeur_axe_principal/2), 'endcap=flat join=round')::geometry(Polygon,2154) as geom_buffer_axe1,
ST_Buffer(axe2_rotated_geometry,(v_buffer.largeur_axe_principal/2), 'endcap=flat join=round')::geometry(Polygon,2154) as geom_buffer_axe2,
ST_Buffer(axe3_rotated_geometry,(v_buffer.largeur_axe_principal/2), 'endcap=flat join=round')::geometry(Polygon,2154) as geom_buffer_axe3,
ST_Buffer(axe4_rotated_geometry,(v_buffer.largeur_axe_travail/2), 'endcap=flat join=round')::geometry(Polygon,2154) as geom_buffer_axe4,
ST_Buffer(v_buffer.wkb_geometry,v_buffer.pied_mat_tampon)::geometry(Polygon,2154) as geom_buffer_pied_mat
FROM ( SELECT v_rotation.ogc_fid,
    v_rotation.nom,
    v_rotation.description,
    v_rotation.orientation_vent_principal,
	v_rotation.longueur_axe_principal,
	v_rotation.largeur_axe_principal,
	v_rotation.longueur_axe_travail,
	v_rotation.largeur_axe_travail,
    v_rotation.rotation_degre,
    v_rotation.id_projet,
	v_rotation.pied_mat_tampon,
	v_rotation.wkb_geometry,
    st_rotate(v_rotation.axe1_geometry, (v_rotation.orientation_vent_principal::double precision * pi() / 180 * -1)::double precision, v_rotation.wkb_geometry)::geometry(LineString,2154) AS axe1_rotated_geometry,
    st_rotate(v_rotation.axe2_geometry, (v_rotation.orientation_vent_principal::double precision * pi() / 180 * -1) ::double precision, v_rotation.wkb_geometry)::geometry(LineString,2154) AS axe2_rotated_geometry,
    st_rotate(v_rotation.axe3_geometry, (v_rotation.orientation_vent_principal::double precision * pi() / 180 * -1)::double precision, v_rotation.wkb_geometry)::geometry(LineString,2154) AS axe3_rotated_geometry,
    st_rotate(v_rotation.axe4_geometry, (v_rotation.orientation_vent_principal::double precision * pi() / 180 * -1)::double precision, v_rotation.wkb_geometry)::geometry(LineString,2154) AS axe4_rotated_geometry
   FROM ( SELECT v_axes.ogc_fid,
            v_axes.nom,
            v_axes.description,
            v_axes.rotation_degre,
            v_axes.id_projet,
		    v_axes.pied_mat_tampon,
		    v_axes.orientation_vent_principal,
		    v_axes.longueur_axe_principal,
			v_axes.largeur_axe_principal,
		    v_axes.longueur_axe_travail,
		    v_axes.largeur_axe_travail,
		    st_setsrid(ST_MakeLine(ST_MakePoint(round(v_axes.cx::numeric,3),round(v_axes.cy::numeric, 3)), ST_MakePoint(round(v_axes.x0::numeric, 3),round(v_axes.y0::numeric, 3))), 2154)::geometry(LineString,2154) AS axe1_geometry,
			st_setsrid(ST_MakeLine(ST_MakePoint(round(v_axes.cx::numeric,3),round(v_axes.cy::numeric, 3)), ST_MakePoint(round(v_axes.x120::numeric, 3),round(v_axes.y120::numeric, 3))), 2154)::geometry(LineString,2154) AS axe2_geometry, 
			st_setsrid(ST_MakeLine(ST_MakePoint(round(v_axes.cx::numeric,3),round(v_axes.cy::numeric, 3)), ST_MakePoint(round(v_axes.x240::numeric, 3),round(v_axes.y240::numeric, 3))), 2154)::geometry(LineString,2154) AS axe3_geometry, 
			st_setsrid(ST_MakeLine(ST_MakePoint(round(v_axes.cx::numeric,3),round(v_axes.cy::numeric, 3)), ST_MakePoint(round(v_axes.x180::numeric, 3),round(v_axes.y180::numeric, 3))), 2154)::geometry(LineString,2154) AS axe4_geometry, 										
			v_axes.wkb_geometry
           FROM ( SELECT v_c.ogc_fid,
                    v_c.nom,
                    v_c.description,
                    v_c.rotation_degre,
                    v_c.id_projet,
				    v_c.pied_mat_tampon,
				    v_c.orientation_vent_principal,
		            v_c.longueur_axe_principal,
			        v_c.largeur_axe_principal,
				    v_c.longueur_axe_travail,
				    v_c.largeur_axe_travail,
                    v_c.cx,
                    v_c.cy,
                    v_c.wkb_geometry,
                    v_c.cx AS x0,
                    v_c.cy + v_c.longueur_axe_principal::double precision AS y0,
                    v_c.cx + sind(60::double precision) * v_c.longueur_axe_principal::double precision AS x120,
                    v_c.cy - cosd(60::double precision) * v_c.longueur_axe_principal::double precision AS y120,
                    v_c.cx - sind(60::double precision) * v_c.longueur_axe_principal::double precision AS x240,
                    v_c.cy - cosd(60::double precision) * v_c.longueur_axe_principal::double precision AS y240,
				    v_c.cx AS x180,
                    v_c.cy - v_c.longueur_axe_travail::double precision AS y180
                   FROM ( SELECT t_i.ogc_fid,
                            t_i.nom,
                            t_i.description,
                            t_i.rotation_degre,
                            t_i.id_projet,
						    t_i.pied_mat_tampon,
						    t_i.orientation_vent_principal,
		                    t_i.longueur_axe_principal,
						    t_i.largeur_axe_principal,
						    t_i.longueur_axe_travail,
						    t_i.largeur_axe_travail,
                            st_x(t_i.wkb_geometry) AS cx,
                            st_y(t_i.wkb_geometry) AS cy,
                            t_i.wkb_geometry
                           FROM ( SELECT met_mast.ogc_fid,
                                    met_mast.nom,
                                    met_mast.description,
								    met_mast.pied_mat_tampon,
                                    met_mast.wkb_geometry,
                                    met_mast.rotation_degre,
                                    met_mast.id_projet,
								    met_mast.orientation_vent_principal,
		                            met_mast.longueur_axe_principal,
								    met_mast.largeur_axe_principal,
								    met_mast.longueur_axe_travail,
								    met_mast.largeur_axe_travail
                                   FROM wind_measurement.met_mast) t_i ) v_c) v_axes) v_rotation) v_buffer) as foo 
	GROUP BY							   
ogc_fid,
nom,
description,
id_projet,
geom_buffer_axe1,
geom_buffer_axe2,
geom_buffer_axe3,
geom_buffer_axe4,
geom_buffer_pied_mat;

ALTER TABLE wind_measurement.v_met_mast_axes_complete
    OWNER TO "sdi_user2";

GRANT ALL ON TABLE wind_measurement.v_met_mast_axes_complete TO "bjo.dec";
GRANT ALL ON TABLE wind_measurement.v_met_mast_axes_complete TO "sdi_user2";
GRANT SELECT ON TABLE wind_measurement.v_met_mast_axes_complete TO PUBLIC;